### ISSUE TITLE
Please Improve the PyBertini Documentation

### ISSUE THREAD

**Issue by cthoyt** [bertiniteam/b2#52]
I've searched through the wiki (and a bit of googling) and haven't found any documentation or examples of the Python API. It would be very helpful to include some!

I think there's a way to propagate documentation from the C++ code (templates?) with Boost but I'm not so familiar with it so I don't have some ready suggestions.

**Comment by ofloveandhate** [comment]
you are absolutely correct.  the documentation for the python bindings is sorely lacking.  i would love to have fully worked examples.

however, since high-level algorithms are not implemented in c++, nor python, i am putting off these examples and documentation for now.  however, if any other people want to help...

that is, documentation is a great place for newcomers to bertini or numerical algebraic geometry to get involved.  it doesn't involve any core coding, so no template meta programming in c++14 (can be a barrier to entry), but instead just using the library, and documenting what you did to solve your problem.  

the documentation for python particularly sucks right now.  the docstrings in the bindings are terrible, to that could be a nice first place.  but i am still learning on how to best generate docstrings and longform help for python.  so if a Boost.Python expert comes along, or any willing party really, maybe they could help Bertiniteam learn about and produce complete documentation for PyBertini?

**Comment by cthoyt** [comment]
I'm a newcomer to both bertini and numerical algebraic geometry. I'd love to help and I will document it as I learn how it works :)

**Comment by ofloveandhate** [comment]
cool, maybe you could hook up with @jacobbond?  he's at purdue right now, and built the python bindings about a week ago.

**Comment by jacobbond** [comment]
The Python test files we really helpful for me as they have working examples.  In particular, I took a look at `python/test/tracking/amptracking_test.py`.  Unfortunately, I don't know enough about homotopy continuation to understand what all of the functions do and it will probably be a month or so before I get the chance to start learning it (my advisor has me working on something over the next month).

I would certainly be interested in helping with the Python documentation though.

**Comment by cthoyt** [comment]
Jacob, would you be able to help me to compile the python bindings with python3? Right now I'm running current mac osx with python2 (/usr/local/Cellar/python3/3.5.2_1/bin/python) and python3 (/usr/local/Cellar/python3/3.5.2_1/bin/python3) installed with brew. Shoot me an email cthoyt at gmail.com if you get a chance!

**Comment by ofloveandhate** [comment]
at this point, i'd like to summon @aliddell.  he's our resident python guy.  this doesn't mean he's an expert on writing the bindings for bertini2, in pybertini.  that's me for now.  instead, alan loves to use python, and helps us write the Python bindings for our C++ corelibrary by advising us on good python practice.

**Comment by ofloveandhate** [comment]
if you run into any issues compiling, please file an issue here at github.com/bertiniteam/b2.  you may be the first non-bertiniteam member to compile against python 3.  i did it a long time ago, but haven't tested against python 3 since then.  your patience and helpfulness is greatly appreciated!

also, feel free to add yourself to

**Comment by ofloveandhate** [comment]
@cthoyt did you try the auto-suggested `LIBS` fix?

**Comment by ofloveandhate** [comment]
in reference to the python 3 issues from before, I am now declaring that python 2 will only be weakly supported.  all testing and development is done against python 3.

**Comment by ofloveandhate** [comment]
it is much improved now, with #112 

i finally have two tutorials and documentation minimally with signature in a nice looking html docset using Sphinx.  the user still has to build the docs themself, but at least they are there.

i am dragging on getting autogenerated docs up for the core and pybertini.  do you happen to already know how to automatically sftp transfer documentation to a server using jenkins, do you?

here, have a ⛵️.  the world is a beautiful place
